### ISSUE TITLE
Add WildBeast (Nokia N900 + Mods)

### ISSUE THREAD

**Issue by Kreyren** [Arcanyx-org/NiXium#119]
Tracking to figure out how to make a NiXium derivation and it's deployment method on The Nokia's Wildest Linux Smartphone, Nokia N900.<sup>2</sup>

<img src="https://github.com/NiXium-org/NiXium/assets/11302521/39d4eea1-8cca-4053-a41e-41f09cc5f86d" width=100% />
<sup>GIF made out of YouTube video [N900 Transformers](https://www.youtube.com/watch?v=erSlMKjCHyk) by @DaVinci57</sup>

Phase 1: Get at least barely functional nix derivation for the device
Phase 2: Perfect it
Phase 3: Hardening

### TODO

* [ ] Submit the u-boot package to Nixpkgs
* [ ] Manage the caching of packages (RFC to NixOS to support the arch)
* [ ] Package `0xFFFF` to Nixpkgs

---

NiXium Role: Personal Device of @Kreyren 

## Bootloader Management

TBD

Seems that the support was dropped

https://github.com/ARM-software/u-boot/tree/master/board/nokia/rx51

It seems that for u-boot it's using config `omap3-n900.dts`.<sup>3</sup>

## File System Management

Standard Nixpkgs file hierarchy for armv7-linux?

## Kernel

PostMarketOS claims that the device runs on Mainline<sup>1</sup>, but they lack the PowerVR GPU Support patches used in Maemo-Leste (devuan distribution)<sup>5.1</sup>.

The kernel repository is for legacy reasons called `droid4-linux`, but contains patches for RX-51 as well.<sup>5.2</sup>

Source code: https://github.com/maemo-leste/droid4-linux where the branch `maemo-6.1.y` is the current stable branch<sup>5.3</sup> where `maemo-6.6.y` should be ready to go and used.

## Firmware

Packaged into blobs for GPU otherwise provided in mainline linux

## Deployment on the device

0xFFFF is used to perform the flashing and interact with the builtin protocols
* https://code.tools/man/1/0xFFFF/#lbAM
* https://github.com/pali/0xFFFF

## Misc

Display uses resolution `800x480`.<sup>4</sup>, wallpapers for maemo are 800x(4*480) -> 800x1920

PostMarketOS recommends 1024 MB SWAP.<sup>4</sup>

DTB is called `omap3-n900`.<sup>4</sup>

Keymaps will likely have to be declared separately.<sup>4</sup> <sup>4.1</sup>

Pali, the creator of 0xFFFF and maintainer of u-boot images for the Nokia N900 rage-quitted from Open-Source development a while ago.<sup>5.4</sup>

## Strategy

1. Package Relevant U-Boot package in Nixpkgs
2. Figure out how to install Minimal NixOS on the device
3. Manage the kernel either through configuration or package it
4. tbd

---

1. [PostMarketOS Wiki - Nokia N900](https://wiki.postmarketos.org/wiki/Nokia_N900_(nokia-n900))
5. [YouTube Video - Taming the Nokia's Wildest Linux Smartphone](https://www.youtube.com/watch?v=G9CFrJnCKqU)
6. [Config file for Omap3-N900 at Upstream U-Boot](https://github.com/u-boot/u-boot/blob/master/dts/upstream/src/arm/ti/omap/omap3-n900.dts)
7. [Source code implementing the device support in PostMarketOS](https://gitlab.com/postmarketOS/pmaports/-/tree/master/device/community/device-nokia-n900)
4.1. [Keymap mapping for the keyboard in PostMarketOS](https://gitlab.com/postmarketOS/pmaports/-/tree/master/device/community/device-nokia-n900/keymaps)
8. [Chat in IRC Libera.chat with maemo-leste community](https://libera.irclog.whitequark.org/maemo-leste/2024-07-24)
5.1. [Info about needed kernel patch for PowerVR GPU](https://libera.irclog.whitequark.org/maemo-leste/2024-07-24#36735673)
5.2. [Kernel repository is called droid4-linux, but contains patches for n900 as well](https://libera.irclog.whitequark.org/maemo-leste/2024-07-24#36735721)
5.3. [maemo-6.1.y claimed to be the current stable branch](https://libera.irclog.whitequark.org/maemo-leste/2024-07-24#36735949)
5.4. [pali rage-quitted from Open-Source development](https://libera.irclog.whitequark.org/maemo-leste/2024-07-26#36745884;)

**Comment by Kreyren** [comment]
Relevant: https://github.com/NixOS/nixpkgs/pull/326677 and https://github.com/NixOS/nixpkgs/issues/326214#issuecomment-2226551947 for playing old cellphone games on the device.

**Comment by Kreyren** [comment]
Relevant: Packaging of Maemo Leste on NixOS https://github.com/NixOS/nixpkgs/issues/328952
